### ISSUE TITLE
移动端浏览器和微信无法使用mui-bar-tab?

### ISSUE THREAD

**Issue by helloxiaocui** [huihoo/e3-h5#3]
在移动端浏览器和微信中打开主页，底部的tab选项卡无法工作，是mui兼容性问题？

**Comment by ColinLiao77** [comment]
是的，当前e3针对的是手机app，所以用的是webview模式，底部的tab切换的对应的是每个webview。如果想在浏览器中正常应用可以将webview改为底部选项卡-div模式。

**Comment by helloxiaocui** [comment]
底部选项卡-div模式需要一次load大量内容，也不是很合适，看来mui想要一次开发多端部署还有很多提升空间。
